# Start from node base image
FROM node:12-alpine as builder

# Set the current working directory inside the container
WORKDIR /build

# Copy package.json, yarn.lock files and download deps
COPY package.json yarn.lock ./
RUN yarn global add @angular/cli
RUN yarn

# Copy sources to the working directory
COPY . .

# Set the node environment
ARG node_env=production
ENV NODE_ENV $node_env

# Build the Node.js app
ARG project
RUN ng build $project